# Generated by Django 4.2.2 on 2024-03-12 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_options_alter_user_referral_code_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='referral',
            name='expiration',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.IntegerField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Реферальный код'),
        ),
    ]
