# Generated by Django 4.2.2 on 2024-03-12 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_referral_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 22, 5, 49), verbose_name='Срок годности'),
        ),
    ]
