# Generated by Django 4.2.2 on 2024-03-13 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_referral_expiration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'ordering': ('id',), 'verbose_name': 'Реферальный код', 'verbose_name_plural': 'Реферальные коды'},
        ),
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Код (5 цифр)'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 18, 52, 31), verbose_name='Срок годности до'),
        ),
    ]
